### ISSUE TITLE
How to use GitHub

### ISSUE THREAD

**Issue by surendra-sketch** [jhu-ep-coursera/fullstack-course4#183]
Sir I'm new here I don't know how to use GitHub in web development, sir please help me to use git repository.

**Comment by danny235** [comment]
Read this https://docs.github.com/en/enterprise/2.13/user/articles/creating-a-new-repository

**Comment by ychaikin** [comment]
@surendra-sketch You can start by following instructions in the course and the course's FAQ. Also, I wrote exactly that in the template for creating new issues here on GitHub. You know, the stuff you erased in order to post this issue. Instead of erasing it, you needed to read it and follow the instructions.
