### ISSUE TITLE
Cannot clone the repo (student from coursera)

### ISSUE THREAD

**Issue by ashersz** [jhu-ep-coursera/fullstack-course4#25]
Here is the message I get
git clone git@github.com:jhu-ep-coursera/fullstack-course4.git
Cloning into 'fullstack-course4'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by kalmanh** [comment]
The easiest way to fix your problem is to just use the https protocol instead of the git protocol. So, 

`git clone https://github.com/jhu-ep-coursera/fullstack-course4.git`

I think the issue you are hitting right now is because of the (lack of) key - https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by ashersz** [comment]
I worked, thanks for the fast answer. You can close the issue
