### ISSUE TITLE
Unable to clone git

### ISSUE THREAD

**Issue by rbeharry** [jhu-ep-coursera/fullstack-course4#90]
Hello, 
I am using Windows, and when I try and clone GIT in the command prompt,  I use this command:
C:\Users\rlbeh>$ git clone https://github.com/rbeharry/coursera-test.git

and I get this message: 
C:\Users\rlbeh>'$' is not recognized as an internal or external command,
''$'' is not recognized as an internal or external command,
operable program or batch file.

When I remove the $ symbol and use this command:

C:\Users\rlbeh>git clone https://github.com/rbeharry/coursera-test.git 
and get this: 
fatal: destination path 'coursera-test' already exists and is not an empty directory.

What does this mean? Why am I not able to clone git? What can I do to correct the problem?

**Comment by naveenkumarkg** [comment]
Hi , 

> C:\Users\rlbeh>$ git clone https://github.com/rbeharry/coursera-test.git
when you are using any linux terminal you'll see $ . you need to ignore the "$ "  and do

> git clone https://github.com/rbeharry/coursera-test.git

the reason why are you getting fatal error is because the same app  or repository is present in your local file system . Kindly delete it or you can use the same if the download is normal with out any error.

or you can do this go to a new folder and repeat this again 

> git clone https://github.com/rbeharry/coursera-test.git
